on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: docker://python:3.10-slim
    steps:
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y \
            git \
            texlive-full \
            python3-pip \
            && rm -rf /var/lib/apt/lists/*
      - uses: actions/checkout@v3
        with:
          ssh-known-hosts: version.aalto.fi
          submodules: recursive
      - name: Install Python dependencies
        run: |
          pip3 install --no-cache-dir -r document/requirements.txt
      - name: Build LaTeX
        run: |
          cd document/src
          latexmk
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: document/src/build/main.pdf
