on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-known-hosts: version.aalto.fi
          submodules: recursive
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            cd src
            latexmk
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: src/main.pdf
